"""create basic table structures

Revision ID: 33b02fd62992
Revises: None
Create Date: 2014-10-26 21:54:31.267932

"""

# revision identifiers, used by Alembic.
revision = '33b02fd62992'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(length=155), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('alias', sa.String(length=155), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('pages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('alias', sa.String(length=155), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('published_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_pages_name'), 'pages', ['name'], unique=False)
    op.create_table('groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('alias', sa.String(length=155), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('groups_users',
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('profiles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('published_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('type', sa.String(length=200), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups_roles',
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('group_id', 'role_id')
    )
    op.create_table('services',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('alias', sa.String(length=155), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('profile_id', sa.Integer(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_profile_id'), 'services', ['profile_id'], unique=False)
    op.create_table('company_profiles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('demo_column', sa.String(length=50), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['profiles.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_demo_column'), 'company_profiles', ['demo_column'], unique=False)
    op.create_table('individual_profiles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('demo_column', sa.String(length=50), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['profiles.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_profiles_demo_column'), 'individual_profiles', ['demo_column'], unique=False)
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('alias', sa.String(length=155), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('profile_id', sa.Integer(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_profile_id'), 'products', ['profile_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_products_profile_id'), table_name='products')
    # op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    # op.drop_index(op.f('ix_individual_profiles_demo_column'), table_name='individual_profiles')
    op.drop_table('individual_profiles')
    # op.drop_index(op.f('ix_company_profiles_demo_column'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # op.drop_index(op.f('ix_services_profile_id'), table_name='services')
    # op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_table('services')
    op.drop_table('groups_roles')
    op.drop_table('profiles')
    op.drop_table('groups_users')
    # op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_table('groups')
    # op.drop_index(op.f('ix_pages_name'), table_name='pages')
    op.drop_table('pages')
    # op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
